### ISSUE TITLE
6章のデモにアクセスできない

### ISSUE THREAD

**Issue by poyopoyo0** [potato4d/nuxt-tech-book#7]
6章のデモにアクセスできなくなっているようです。
↓

https://potato4d.github.io/nuxt-tech-book/examples/section06/06_API_And_Proxy
![section06_demo_01](https://user-images.githubusercontent.com/10114122/39397383-50f31ee8-4b39-11e8-8713-0c54c9a8bd8e.png)

https://potato4d.github.io/nuxt-tech-book/examples/section06/06_PWA/
![section06_demo_02](https://user-images.githubusercontent.com/10114122/39397379-48f93efc-4b39-11e8-9a4f-e81f22705317.png)

**Comment by potato4d** [comment]
@poyopoyo0 
ご連絡いただきありがとうございます。修正いたしました。

**Comment by poyopoyo0** [comment]
@potato4d 
ご対応頂きまして、ありがとうございます。

すみません、 https://potato4d.github.io/nuxt-tech-book/examples/section06/06_API_And_Proxy のリンク先の https://nuxt-techbook-06-proxy.herokuapp.com/ にアクセスすると、
![nuxt-techbook-06-01-error](https://user-images.githubusercontent.com/10114122/39455869-d1091bf6-4d1d-11e8-8df4-5d82296f83f4.png)
のようにエラー表示がされてしまいます。
こちらについても、ご対応頂けますでしょうか…？
